### PR TITLE
Support for React 16

### PR DESCRIPTION
**Pull request by Mathspy**
Basic support for React 16.0:
- [x] Use ``enzyme 3`` and  ``enzyme-adapter-react-16``
- [x] Install ``react-test-renderer`` since  ``enzyme-adapter-react-16`` depends on it
- [x] Added ``react-dom`` as a peerDependency, why wasn't it so originally anyway?
- [x] Added ``react-dom-factories`` for the few tests that requires it
- [x] Update tests to use the adapter and ``react-dom-factories``

As far as I am concerned there is no way to tell npm that if someone has a peerDependency of 16 then it has to install ``prop-types`` otherwise it ignores that (since it will be installed with React pre-16 by default) so I guess the way to go here is to drop support for pre-16 moving forward?

Closes https://github.com/matthewwithanm/react-inlinesvg/issues/67

### CODE REVIEW

**Comment by Mathspy** [comment]
Updated my project to use my fork and it looks like everything is working fine


For anyone interested in temporary solution (that you will have to undo later):
Replace this (in your ``package.json``)
```
"react-inlinesvg": "^0.6.0"
```
with this:
```
"react-inlinesvg": "Mathspy/react-inlinesvg"
```

**Comment by gilbarbara** [comment]
Hey,

Did you test #67?

Btw, suggesting people to use your fork isn't nice...

**Comment by Mathspy** [comment]
> Btw, suggesting people to use your fork isn't nice...

I am sorry if my suggestion sounded like I am advertising my fork or anything like that, I was afraid you and the other maintainers might be busy (because we all are, really) and might need some time to get back to updating this package so I left that message there in case anyone stumbles upon this and needs to get this working with a temporary workaround

> Did you test #67?

The issue doesn't really offer any reproducible examples, but I am pretty confident it simply has to do with the removal of some internals from ``react`` in the new version. 
If you were to compare the output of ``standalone/react-inlinesvg.js`` you will notice the new version complied with React 16 no longer has the culpit function ``enqueueCallback``

> ``react``, ``react-dom`` and ``prop-types`` should be in peerDependencies not dependencies

Like I mentioned, ``react`` no longer comes by default with ``prop-types`` which will result into people having to manually install ``prop-types`` into their projects to use this package, which is kind of against the way node packages work in general because ``prop-types`` isn't really something everyone using this will be using or wanting to use

I personally believe the right course of action is to bump major and specify that ``v0.6.2`` is compatible with ``react 0.14/15`` while ``v1.0.0`` upwards will work only with ``react 16+`` and in case of any important updates they could always be cherry picked into an ``v0.x`` branch

**Comment by andrepcg** [comment]
When is this PR going to get merged? My initial tests is that everything works correctly. Was having issues with #67 but not anymore

**Comment by gilbarbara** [comment]
@Mathspy 
Despite React not including `prop-types` anymore, it's better to keep as a peerDependency. If every package requires it's own version of it, a project could end up with multiple copies of it.

**Comment by gilbarbara** [comment]
@andrepcg changing the React version wouldn't make any difference besides the silly warning on install.

**Comment by Mathspy** [comment]
@gilbarbara The recommended pattern by Facebook is to use it as a dependency not as a peerDependency as can be seen from here https://github.com/facebook/prop-types/issues/44 and here https://github.com/facebook/prop-types/issues/4
The argument is that as long as everyone is using ``^`` to match ``prop-types`` all libraries using it should be able to share the same version, this has been the behaviour since ``npm`` 3+ and always been the way ``yarn`` worked
Quoting Dan:
> If everyone puts ``^`` in the version then no, both npm and Yarn should deduplicate it. Now, in practice unfortunately this doesn’t always happen in npm 2, but it’s not even in Node LTS so I think it should be okay.

**Comment by gilbarbara** [comment]
Yeah, I'm definitely not sold on the idea to make this library only compatible with React 16 and up just to be cool.
I prefer to just add the `|| ^16.0.0` to peerDependencies and not break shit.
@matthewwithanm any thoughts?

**Comment by matthewwithanm** [comment]
@gilbarbara I'm cool with whatever you think best 😊

**Comment by dzek69** [comment]
@gilbarbara personally I'm very grateful for @Mathspy to provide his fork as a workaround. It's very common problem - packages die very fast and in recent year I've made about 10 forks with fixes of random libraries that authors abadoned and are not even checking the PRs, but they're still pretty good, just need one small fix.

**Comment by dzek69** [comment]
Nope.
This library just doesn't work with React 16, because it tries to use React.PropTypes.something, but React.PropTypes is undefined with React 16.

That's why I'm here, not because of warning during install.

**Comment by gilbarbara** [comment]
@dzek69 It does, I'm using `0.6.2` in a couple of React 16 projects already.

**Comment by gilbarbara** [comment]
added in `0.7.0`

**Pull request merged**
