### PR TITLE
rewrite src code in ES2015 and add `shouldComponentUpdate`

### PR DESCRIPTION
**Pull request by gilbarbara**

### CODE REVIEW

**Comment by matthewwithanm** [comment]
Wow awesome! How do you feel about me adding you as a contrib?

**Comment by gilbarbara** [comment]
hey @matthewwithanm 
Yay, I'm glad you liked! It would be great to help as a collaborator.

**Comment by gilbarbara** [comment]
I've found some little bugs while testing, let me work on those and I'll commit a fix later.

**Comment by gilbarbara** [comment]
Hey @matthewwithanm 
Thanks for the privileges! 👍 

I think I've fixed everything. Can we merge it?

**Comment by gilbarbara** [comment]
done! :)

**Comment by matthewwithanm** [comment]
👍

**Pull request merged**
