### PR TITLE
Alternative to getComponentID as _rootNodeID is not longer supported on latest version of React

### PR DESCRIPTION
**Pull request by juancabrera**
##### Updates:
- update versions of gulp & gulp-connect (and made small code tweaks in order to support these versions)
- removing getComponentID
- adding getHash
- now its generating a hash from the SVG path instead of using getComponentID and _rootNodeID

##### Note:
Just created an small hash generator method (```getHash```), other option is to use [object-hash](https://www.npmjs.com/package/object-hash). Let me know what you think.

### CODE REVIEW

**Comment by matthewwithanm** [comment]
Looks great! Exactly what I had in mind, thanks!

If you wouldn't mind, though, do you think you could amend 5383e7e736a76d92e18359aeecca100f13920738 and b04f35de187cb4f8d3ee88e575d19b5728a89b24 to omit the compiled code? Also, we could probably lose e473f95 and 909975a since they're just canceling each other out, but I can do that when I merge.

**Comment by juancabrera** [comment]
Not sure what you mean for 5383e7e736a76d92e18359aeecca100f13920738 and b04f35de187cb4f8d3ee88e575d19b5728a89b24. But yeah, feel free to do/fix/tweak whatever you need to on the merge!

**Comment by juancabrera** [comment]
let me know!
would love to get this merged in so I can start using it.

**Comment by matthewwithanm** [comment]
Sorry, I was just asking if you could update the commits so they don't include the generated standalone build. Generally, I try to avoid committing compiled code along with the changes since it muddies up the history. Honestly, I'd much prefer to not commit it altogether, but bower.

I rebase, amended your commits, merged and pushed to master so we should be good now. Thanks!

**Comment by juancabrera** [comment]
:ok_hand: — thank you! :sparkles:

**Pull request closed without merging**
